### ISSUE TITLE
TP1-Automata_Constantes_C

### ISSUE THREAD

**Issue by LucasLSch** [GRodriguezPardo/2020_K2031_Grupo_4#3]
**_Solicitamos corrección_**
@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Muy bien trabajo! . 

El menú que armaron está muy bien, pero debo hacerles una aclaración importante para los trabajos, deben ajustarse a lo que se les pide en la consigna. En este caso el archivo de entrada tenía un nombre "entrada.txt" y el de salida "salida.txt". Ustedes hicieron algo más genérico que está muy bien, pero deben comprender que no es lo pedido en la consigna. Tengan eso presente en general para otros trabajos. No es que quiera limitar su capacidad de explayarse, pero en caso de agregar funcionalidades que no se están pidiendo deberían aclararlo en el issue

Mi experiencia como usuario del programa, es que yo pensaba utilizar mi archivo "entrada.txt", y tuve que entender que es lo que me pedía, darle la ruta, darle el nombre del archivo, etc. Se entiende? Tiene que verlo desde el lado del usuario además del lado del programador.

Nota: 10 !

Excelente trabajo, pero tengan presente lo que les comento. Si agregan funcionalidad, como por ejemplo, un menú. Aclarenlo en el issue.

@LucasLSch @CarolinaSeoane @FacuVerge @GRodriguezPardo  @AgusBazzi @AlejandroMorgante
