### ISSUE TITLE
Entrega TP2 AFP 

### ISSUE THREAD

**Issue by AgusBazzi** [GRodriguezPardo/2020_K2031_Grupo_4#4]
### Buen día, solicitamos corrección del TP2.
@santiagoferreiros 

**Features del programa:**
- Menú
- Detección de errores y su clasificación (y su posición en caso de ser necesario)
- Ingreso de expresión con asignación de memoria dinámica
- Supresión de espacios innecesarios (que no ocasionan errores)
- Detección de espacios erróneos

**Comment by santiagoferreiros** [comment]
Estimados,

Excelente trabajo !
Si ingreso a la opción 3 sin haber puesto ninguna expresión sale directamente del programa.
Encuentran bien la posición del error, en algunos casos no describe a que se debe, en otro si, como por ejemplo cuando falta cerrar algún paréntesis.

Felicitaciones. Han hecho un excelente trabajo =)

Nota 9

@AgusBazzi @CarolinaSeoane @LucasLSch @FacuVerge @AlejandroMorgante
