### ISSUE TITLE
Entrega TP3

### ISSUE THREAD

**Issue by LucasLSch** [GRodriguezPardo/2020_K2031_Grupo_4#5]
@santiagoferreiros solicitamos corrección

Utilizamos un archivo superfunciones.c donde se encuentran las funciones que utilizamos en el programa.
El programa lee los lexemas de un archivo entrada.c y genera el archivo reporte.txt ademas de mostrar el reporte por consola.

**Comment by santiagoferreiros** [comment]
Estimado equipo,

Excelente trabajo.

Les pido para la próxima entrega que incluyan un archivo de prueba "entrada.c" así me resulta más sencilla la corrección. Es un simple detalle. Lo estuve probando un funciona muy bien todo =)

Muy prolijo y ordenado el código.

Para el TP integrador agregaremos las directivas del precompilador y ya estamos! 
Vamos por más !

Saludos,
Nota: 9

Santiago
