### ISSUE TITLE
Entrega TP4

### ISSUE THREAD

**Issue by GRodriguezPardo** [GRodriguezPardo/2020_K2031_Grupo_4#6]
**Buen día, solicitamos corrección del TP4.**
@santiagoferreiros

Features del programa:
- Hay algunos features que solo funcionan en bash. Por lo que tenemos un makefile que genera la version con los features del bash y un .bat para la version que corre en el CMD **(Leer ReadMe de la carpeta de TP4)**.
- Pedido de archivo de entrada para analizar. (Debe contener la extension del archivo)
- Separacion de errores lexicos y sintacticos.
- Gramatica de C utilizada --> https://www.lysator.liu.se/c/ANSI-C-grammar-y.html y PDF ubicado en el repositorio

**Comment by santiagoferreiros** [comment]
Estimado grupo

Estoy teniendo inconvenientes al ejecutar el analizador sintáctico

Me aparece lo siguiente

![image](https://user-images.githubusercontent.com/46604718/95929463-6e34a280-0d9a-11eb-8c8f-3bd0023710ea.png)

Seguí las instrucciones que me han indicado en el archivo
Les propongo que como alternativa ya deje en el repositorio el archivo ejecutable y un archivo de prueba.

Saludos,

Santiago

**Comment by crisszkutnik** [comment]
Hola Santi!

Ahi arreglamos el error. Era un pequeño inconveniente con la posicion del token error y las directivas de preprocesamiento. Ahi el programa deberia ejecutarse completamente aunque encuentre errores.

Particularmente el `lex.yy.c` tiene varios errores sintacticos ya que hace uso de muchos tipos de datos definidos con TYPEDEF que, como dijimos en el README, se necesita una TS para implementar de forma completa.

Perdon por el inconveniente!

**Comment by santiagoferreiros** [comment]
Estimados,

He vuelto a probar el trabajo. Ahora si pode ejecutarlo.
Nota: 9

Sigan trabajando así! Vamos por más.
No tengo ninguna devolución en específico para hacer, únicamente les pido atención con el manejo de la gramática a la hora de implementar las funciones y la gestión de los errores. Pero por ahora todo va muy bien.

Saludos!
